### PR TITLE
Updated to 2.1.0

### PR DESCRIPTION
**Pull request by stanmart**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by stanmart** [comment]
@conda-forge-admin, please rerender

**Comment by stanmart** [comment]
@conda-forge-admin, please rerender

**Review by gforsyth — APPROVED** [review]
This looks good @stanmart -- thanks for making these changes!  Do you want to add yourself to the list of recipe maintainers?

**Comment by stanmart** [comment]
Thanks for the quick review! I haven't thought about adding myself as a maintainer as it is my first try at updating a recipe, but if you feel that it would be helpful, then sure, why not.

**Comment by gforsyth** [comment]
> Thanks for the quick review! I haven't thought about adding myself as a maintainer as it is my first try at updating a recipe, but if you feel that it would be helpful, then sure, why not.

I'd posit that you are already helping to maintain it :grin: so might as well make it official.

**Comment by stanmart** [comment]
Alright then, thanks 🙂 Do I only need to modify `meta.yml` and ask conda-forge-admin to rerender?

**Comment by stanmart** [comment]
@conda-forge-admin, please rerender

**Comment by gforsyth** [comment]
Thanks, @stanmart!

**Pull request merged**
